name: Python application

on: [push]

jobs:
  build:
  
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]


    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        

    - name: Install dependencies
      shell: bash
      run: pip install -r requirements.txt
      
    - name: Server and Tests
      shell: bash
      run: ./manage.py runserver > /dev/null 2>&1 & pytest product/tests/ order/tests/
